version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - app-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.1
    volumes:
      - ./logstash/config:/usr/share/logstash/config
    depends_on:
      - elasticsearch
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  warehouse-webapi:
    build:
      context: .
      dockerfile: src/Majestic.WarehouseService.WebApi/Dockerfile
    expose:
      - "80" 
    depends_on:
      - rabbitmq
      - redis
      - sql_server
      - logstash
    networks:
      - app-network

  warehouse-hostedservice:
    build:
      context: .
      dockerfile: src/Majestic.WarehouseService.HostedService/Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - sql_server
      - logstash
    networks:
      - app-network

  sql_server:
    image: "mcr.microsoft.com/mssql/server"
    user: root
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql/data
    networks:
      - app-network

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "8991:80"
    depends_on:
      - warehouse-webapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

volumes:
  sql_data:
    driver: local

networks:
  app-network:
    driver: bridge
